import { HttpRequest } from '../types';
import { toast } from '../store/useToastStore';

export type ExportFormat = 'har' | 'json' | 'csv' | 'curl' | 'sh';

export async function exportRequests(
  requests: HttpRequest[],
  format: ExportFormat = 'har',
  baseFilename: string = 'httpeek-export'
): Promise<boolean> {
  if (!requests || requests.length === 0) {
    toast.warning('No requests selected to export');
    return false;
  }

  const cleanName = baseFilename.replace(/[^a-zA-Z0-9_-]/g, '_');
  const timestamp = Date.now();

  try {
    let data = '';
    let mimeType = 'application/json';
    let extension = format === 'curl' || format === 'sh' ? 'sh' : format;

    // Check if Wails backend ExportRequestsAs bridge exists
    if ((window as any).go?.main?.App?.ExportRequestsAs) {
      data = await (window as any).go.main.App.ExportRequestsAs(requests, format === 'curl' ? 'sh' : format);
    } else if (format === 'har' && (window as any).go?.main?.App?.ExportHAR) {
      data = await (window as any).go.main.App.ExportHAR(requests);
    } else {
      // Client-side fallback generator
      if (format === 'har' || format === 'json') {
        data = JSON.stringify(requests, null, 2);
        mimeType = 'application/json';
      } else if (format === 'csv') {
        data = generateCSV(requests);
        mimeType = 'text/csv';
      } else {
        data = generateCurlScript(requests);
        mimeType = 'text/x-shellscript';
      }
    }

    if (format === 'csv') mimeType = 'text/csv';
    else if (format === 'curl' || format === 'sh') mimeType = 'text/x-shellscript';
    else mimeType = 'application/json';

    // Trigger browser file download
    const blob = new Blob([data], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${cleanName}_${timestamp}.${extension}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success(
      `Exported ${requests.length} ${requests.length === 1 ? 'request' : 'requests'}`,
      `${cleanName}_${timestamp}.${extension}`
    );
    return true;
  } catch (e: any) {
    toast.error('Export Failed', e?.message || String(e));
    return false;
  }
}

function generateCSV(requests: HttpRequest[]): string {
  const lines = ['ID,Method,URL,Status,Duration(ms),StartTime,ContentType,Size(B)'];
  requests.forEach((r) => {
    const id = r.id || '';
    const method = r.method || 'GET';
    const url = (r.url || '').replace(/"/g, '""');
    const status = r.response?.statusCode || 0;
    const dur = r.durationMs || r.duration || 0;
    const start = (r.startTime || '').replace(/"/g, '""');
    const ct = (r.response?.contentType || '').replace(/"/g, '""');
    const size = r.response?.bodySize || 0;
    lines.push(`"${id}","${method}","${url}",${status},${dur},"${start}","${ct}",${size}`);
  });
  return lines.join('\n');
}

function generateCurlScript(requests: HttpRequest[]): string {
  const lines = ['#!/usr/bin/env bash\n# Generated by HTTPeek\n'];
  requests.forEach((r) => {
    let cmd = `curl -X ${r.method || 'GET'} "${r.url}"`;
    if (r.headers) {
      Object.entries(r.headers).forEach(([k, rawVal]) => {
        const val = Array.isArray(rawVal) ? rawVal.join(', ') : String(rawVal);
        cmd += ` \\\n  -H "${k}: ${val.replace(/"/g, '\\"')}"`;
      });
    }
    const body = r.bodyString || r.body;
    if (body) {
      cmd += ` \\\n  --data-raw "${String(body).replace(/"/g, '\\"')}"`;
    }
    lines.push(cmd + '\n');
  });
  return lines.join('\n');
}
