// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortBreakpoint(arg1, arg2) {
  return window['go']['main']['App']['AbortBreakpoint'](arg1, arg2);
}

export function AddBlockRule(arg1) {
  return window['go']['main']['App']['AddBlockRule'](arg1);
}

export function AddHostToBlacklist(arg1) {
  return window['go']['main']['App']['AddHostToBlacklist'](arg1);
}

export function AddHostToWhitelist(arg1) {
  return window['go']['main']['App']['AddHostToWhitelist'](arg1);
}

export function AttachJVM(arg1, arg2) {
  return window['go']['main']['App']['AttachJVM'](arg1, arg2);
}

export function CheckCAInstalled() {
  return window['go']['main']['App']['CheckCAInstalled']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CreateNewSession(arg1) {
  return window['go']['main']['App']['CreateNewSession'](arg1);
}

export function DeleteFavorite(arg1) {
  return window['go']['main']['App']['DeleteFavorite'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeployFridaServer(arg1) {
  return window['go']['main']['App']['DeployFridaServer'](arg1);
}

export function DetectJavaInstallations() {
  return window['go']['main']['App']['DetectJavaInstallations']();
}

export function DetectLaunchableApps() {
  return window['go']['main']['App']['DetectLaunchableApps']();
}

export function DisconnectMobileDevice(arg1) {
  return window['go']['main']['App']['DisconnectMobileDevice'](arg1);
}

export function DownloadADBIfMissing() {
  return window['go']['main']['App']['DownloadADBIfMissing']();
}

export function ExitApp() {
  return window['go']['main']['App']['ExitApp']();
}

export function ExportHAR(arg1) {
  return window['go']['main']['App']['ExportHAR'](arg1);
}

export function ExportRequestsAs(arg1, arg2) {
  return window['go']['main']['App']['ExportRequestsAs'](arg1, arg2);
}

export function ExportRootCA() {
  return window['go']['main']['App']['ExportRootCA']();
}

export function ExportRules() {
  return window['go']['main']['App']['ExportRules']();
}

export function GetAllRules() {
  return window['go']['main']['App']['GetAllRules']();
}

export function GetBlockRules() {
  return window['go']['main']['App']['GetBlockRules']();
}

export function GetBreakpointRules() {
  return window['go']['main']['App']['GetBreakpointRules']();
}

export function GetCADetails() {
  return window['go']['main']['App']['GetCADetails']();
}

export function GetConnectedMobileDevices() {
  return window['go']['main']['App']['GetConnectedMobileDevices']();
}

export function GetCryptoRules() {
  return window['go']['main']['App']['GetCryptoRules']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetHostFilterConfig() {
  return window['go']['main']['App']['GetHostFilterConfig']();
}

export function GetHostsRules() {
  return window['go']['main']['App']['GetHostsRules']();
}

export function GetJavaGlobalProxyStatus() {
  return window['go']['main']['App']['GetJavaGlobalProxyStatus']();
}

export function GetLaunchableAppCAs() {
  return window['go']['main']['App']['GetLaunchableAppCAs']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function GetLogDir() {
  return window['go']['main']['App']['GetLogDir']();
}

export function GetLogFilePath() {
  return window['go']['main']['App']['GetLogFilePath']();
}

export function GetMobileAPIToken() {
  return window['go']['main']['App']['GetMobileAPIToken']();
}

export function GetMockRules() {
  return window['go']['main']['App']['GetMockRules']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetReportConfigs() {
  return window['go']['main']['App']['GetReportConfigs']();
}

export function GetRewriteRules() {
  return window['go']['main']['App']['GetRewriteRules']();
}

export function GetScriptRules() {
  return window['go']['main']['App']['GetScriptRules']();
}

export function GetSessionRequests(arg1) {
  return window['go']['main']['App']['GetSessionRequests'](arg1);
}

export function GetStartupFile() {
  return window['go']['main']['App']['GetStartupFile']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetThrottleConfig() {
  return window['go']['main']['App']['GetThrottleConfig']();
}

export function GetThrottleProfiles() {
  return window['go']['main']['App']['GetThrottleProfiles']();
}

export function ImportHAR(arg1, arg2) {
  return window['go']['main']['App']['ImportHAR'](arg1, arg2);
}

export function ImportRules(arg1) {
  return window['go']['main']['App']['ImportRules'](arg1);
}

export function InstallAndroidRootCA(arg1) {
  return window['go']['main']['App']['InstallAndroidRootCA'](arg1);
}

export function InstallCertToAndroid(arg1) {
  return window['go']['main']['App']['InstallCertToAndroid'](arg1);
}

export function InstallCertToJava(arg1) {
  return window['go']['main']['App']['InstallCertToJava'](arg1);
}

export function InstallRootCA() {
  return window['go']['main']['App']['InstallRootCA']();
}

export function IsCAInstalled() {
  return window['go']['main']['App']['IsCAInstalled']();
}

export function IsHARAssociated() {
  return window['go']['main']['App']['IsHARAssociated']();
}

export function LaunchAndIntercept(arg1) {
  return window['go']['main']['App']['LaunchAndIntercept'](arg1);
}

export function LaunchBrowserInterceptor(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchBrowserInterceptor'](arg1, arg2, arg3);
}

export function LaunchCustomApp(arg1) {
  return window['go']['main']['App']['LaunchCustomApp'](arg1);
}

export function LaunchElectronApp(arg1, arg2) {
  return window['go']['main']['App']['LaunchElectronApp'](arg1, arg2);
}

export function LaunchFrida(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchFrida'](arg1, arg2, arg3);
}

export function LaunchFridaAttach(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchFridaAttach'](arg1, arg2, arg3);
}

export function LaunchJVMApp(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchJVMApp'](arg1, arg2, arg3);
}

export function LaunchTerminal(arg1, arg2) {
  return window['go']['main']['App']['LaunchTerminal'](arg1, arg2);
}

export function ListADBDevices() {
  return window['go']['main']['App']['ListADBDevices']();
}

export function ListActiveExternalRuns() {
  return window['go']['main']['App']['ListActiveExternalRuns']();
}

export function ListAndroidInstalledApps(arg1) {
  return window['go']['main']['App']['ListAndroidInstalledApps'](arg1);
}

export function ListAndroidRunningApps(arg1) {
  return window['go']['main']['App']['ListAndroidRunningApps'](arg1);
}

export function ListExternalRuns() {
  return window['go']['main']['App']['ListExternalRuns']();
}

export function ListJVMTargets() {
  return window['go']['main']['App']['ListJVMTargets']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LogFromUI(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogFromUI'](arg1, arg2, arg3, arg4);
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function RegisterHARAssociation() {
  return window['go']['main']['App']['RegisterHARAssociation']();
}

export function RepeatRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['RepeatRequest'](arg1, arg2, arg3);
}

export function ReplayRequest(arg1) {
  return window['go']['main']['App']['ReplayRequest'](arg1);
}

export function ResolveADBPath() {
  return window['go']['main']['App']['ResolveADBPath']();
}

export function ResumeBreakpoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResumeBreakpoint'](arg1, arg2, arg3);
}

export function ReverseADBPort(arg1, arg2) {
  return window['go']['main']['App']['ReverseADBPort'](arg1, arg2);
}

export function SelectJavaFolder() {
  return window['go']['main']['App']['SelectJavaFolder']();
}

export function SendCustomRequest(arg1) {
  return window['go']['main']['App']['SendCustomRequest'](arg1);
}

export function SendRemoteMobileCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendRemoteMobileCommand'](arg1, arg2, arg3);
}

export function SetBlockRules(arg1) {
  return window['go']['main']['App']['SetBlockRules'](arg1);
}

export function SetBreakpointRules(arg1) {
  return window['go']['main']['App']['SetBreakpointRules'](arg1);
}

export function SetCryptoRules(arg1) {
  return window['go']['main']['App']['SetCryptoRules'](arg1);
}

export function SetExternalProxy(arg1) {
  return window['go']['main']['App']['SetExternalProxy'](arg1);
}

export function SetHostFilterConfig(arg1) {
  return window['go']['main']['App']['SetHostFilterConfig'](arg1);
}

export function SetHostsRules(arg1) {
  return window['go']['main']['App']['SetHostsRules'](arg1);
}

export function SetJavaGlobalProxy(arg1) {
  return window['go']['main']['App']['SetJavaGlobalProxy'](arg1);
}

export function SetMockRules(arg1) {
  return window['go']['main']['App']['SetMockRules'](arg1);
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}

export function SetProxyPort(arg1) {
  return window['go']['main']['App']['SetProxyPort'](arg1);
}

export function SetReportConfigs(arg1) {
  return window['go']['main']['App']['SetReportConfigs'](arg1);
}

export function SetRewriteRules(arg1) {
  return window['go']['main']['App']['SetRewriteRules'](arg1);
}

export function SetSSLEnabled(arg1) {
  return window['go']['main']['App']['SetSSLEnabled'](arg1);
}

export function SetScriptRules(arg1) {
  return window['go']['main']['App']['SetScriptRules'](arg1);
}

export function SetSystemProxy(arg1) {
  return window['go']['main']['App']['SetSystemProxy'](arg1);
}

export function SetThrottleConfig(arg1) {
  return window['go']['main']['App']['SetThrottleConfig'](arg1);
}

export function SetThrottleProfiles(arg1) {
  return window['go']['main']['App']['SetThrottleProfiles'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function StartADBInterception(arg1) {
  return window['go']['main']['App']['StartADBInterception'](arg1);
}

export function StartProxy(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2, arg3);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function StopADBInterception(arg1) {
  return window['go']['main']['App']['StopADBInterception'](arg1);
}

export function StopFrida(arg1) {
  return window['go']['main']['App']['StopFrida'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function SyncRulesToMobile(arg1) {
  return window['go']['main']['App']['SyncRulesToMobile'](arg1);
}

export function ToggleFavoriteRequest(arg1, arg2) {
  return window['go']['main']['App']['ToggleFavoriteRequest'](arg1, arg2);
}

export function ToolboxAES(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ToolboxAES'](arg1, arg2, arg3, arg4, arg5);
}

export function ToolboxCertHash(arg1) {
  return window['go']['main']['App']['ToolboxCertHash'](arg1);
}

export function ToolboxEncode(arg1, arg2) {
  return window['go']['main']['App']['ToolboxEncode'](arg1, arg2);
}

export function ToolboxRSA(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ToolboxRSA'](arg1, arg2, arg3, arg4);
}

export function ToolboxRunJS(arg1, arg2) {
  return window['go']['main']['App']['ToolboxRunJS'](arg1, arg2);
}

export function UninstallCertFromJava(arg1) {
  return window['go']['main']['App']['UninstallCertFromJava'](arg1);
}

export function UninstallRootCA() {
  return window['go']['main']['App']['UninstallRootCA']();
}

export function UnregisterHARAssociation() {
  return window['go']['main']['App']['UnregisterHARAssociation']();
}

export function WriteLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteLog'](arg1, arg2, arg3);
}
