// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {interceptor} from '../models';
import {storage} from '../models';
import {cert} from '../models';
import {proxy} from '../models';
import {logger} from '../models';

export function AbortBreakpoint(arg1:string,arg2:boolean):Promise<void>;

export function AddBlockRule(arg1:interceptor.BlockRule):Promise<void>;

export function AddHostToBlacklist(arg1:string):Promise<void>;

export function AddHostToWhitelist(arg1:string):Promise<void>;

export function CheckCAInstalled():Promise<boolean>;

export function ClearLogs():Promise<void>;

export function CreateNewSession(arg1:string):Promise<storage.Session>;

export function DeleteSession(arg1:string):Promise<void>;

export function DetectJavaInstallations():Promise<Array<cert.JavaInstallation>>;

export function DisconnectMobileDevice(arg1:string):Promise<void>;

export function ExitApp():Promise<void>;

export function ExportHAR(arg1:Array<proxy.HttpRequest>):Promise<string>;

export function ExportRequestsAs(arg1:Array<proxy.HttpRequest>,arg2:string):Promise<string>;

export function ExportRootCA():Promise<string>;

export function GetAllRules():Promise<Record<string, any>>;

export function GetBlockRules():Promise<Array<interceptor.BlockRule>>;

export function GetBreakpointRules():Promise<Array<interceptor.BreakpointRule>>;

export function GetCADetails():Promise<Record<string, any>>;

export function GetConnectedMobileDevices():Promise<Array<proxy.MobileDeviceInfo>>;

export function GetCryptoRules():Promise<Array<interceptor.CryptoRule>>;

export function GetFavorites():Promise<Array<proxy.HttpRequest>>;

export function GetHostFilterConfig():Promise<interceptor.HostFilterConfig>;

export function GetHostsRules():Promise<Array<interceptor.HostRule>>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetLogDir():Promise<string>;

export function GetLogFilePath():Promise<string>;

export function GetMockRules():Promise<Array<interceptor.MapRule>>;

export function GetProxyStatus():Promise<Record<string, any>>;

export function GetRecentLogs(arg1:number):Promise<Array<logger.Entry>>;

export function GetReportConfigs():Promise<Array<interceptor.ReportServerConfig>>;

export function GetRewriteRules():Promise<Array<interceptor.RewriteRule>>;

export function GetScriptRules():Promise<Array<interceptor.ScriptRule>>;

export function GetSessionRequests(arg1:string):Promise<Array<proxy.HttpRequest>>;

export function GetStartupFile():Promise<string>;

export function GetStatus():Promise<Record<string, any>>;

export function GetThrottleConfig():Promise<interceptor.ThrottleConfig>;

export function GetThrottleProfiles():Promise<Array<interceptor.ThrottleProfile>>;

export function ImportHAR(arg1:string,arg2:string):Promise<storage.Session>;

export function InstallAndroidRootCA(arg1:string):Promise<cert.AndroidInstallResult>;

export function InstallCertToAndroid(arg1:string):Promise<cert.AndroidInstallResult>;

export function InstallCertToJava(arg1:string):Promise<void>;

export function InstallRootCA():Promise<void>;

export function IsCAInstalled():Promise<boolean>;

export function IsHARAssociated():Promise<boolean>;

export function ListADBDevices():Promise<Array<cert.ADBDeviceInfo>>;

export function ListSessions():Promise<Array<storage.Session>>;

export function LogFromUI(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function OpenLogFolder():Promise<void>;

export function RegisterHARAssociation():Promise<void>;

export function RepeatRequest(arg1:proxy.HttpRequest,arg2:number,arg3:number):Promise<Array<proxy.HttpResponse>>;

export function ReplayRequest(arg1:proxy.HttpRequest):Promise<proxy.HttpResponse>;

export function ResumeBreakpoint(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function SelectJavaFolder():Promise<cert.JavaInstallation>;

export function SendCustomRequest(arg1:string):Promise<proxy.HttpResponse>;

export function SetBlockRules(arg1:Array<interceptor.BlockRule>):Promise<void>;

export function SetBreakpointRules(arg1:Array<interceptor.BreakpointRule>):Promise<void>;

export function SetCryptoRules(arg1:Array<interceptor.CryptoRule>):Promise<void>;

export function SetExternalProxy(arg1:Record<string, any>):Promise<void>;

export function SetHostFilterConfig(arg1:interceptor.HostFilterConfig):Promise<void>;

export function SetHostsRules(arg1:Array<interceptor.HostRule>):Promise<void>;

export function SetMockRules(arg1:Array<interceptor.MapRule>):Promise<void>;

export function SetPort(arg1:number):Promise<void>;

export function SetProxyPort(arg1:number):Promise<void>;

export function SetReportConfigs(arg1:Array<interceptor.ReportServerConfig>):Promise<void>;

export function SetRewriteRules(arg1:Array<interceptor.RewriteRule>):Promise<void>;

export function SetSSLEnabled(arg1:boolean):Promise<void>;

export function SetScriptRules(arg1:Array<interceptor.ScriptRule>):Promise<void>;

export function SetSystemProxy(arg1:boolean):Promise<void>;

export function SetThrottleConfig(arg1:interceptor.ThrottleConfig):Promise<void>;

export function SetThrottleProfiles(arg1:Array<interceptor.ThrottleProfile>):Promise<void>;

export function Start():Promise<void>;

export function StartProxy(arg1:number,arg2:boolean,arg3:boolean):Promise<void>;

export function Stop():Promise<void>;

export function StopProxy():Promise<void>;

export function ToggleFavoriteRequest(arg1:string,arg2:boolean):Promise<void>;

export function ToolboxAES(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ToolboxCertHash(arg1:string):Promise<Record<string, any>>;

export function ToolboxEncode(arg1:string,arg2:string):Promise<string>;

export function ToolboxRSA(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ToolboxRunJS(arg1:string,arg2:string):Promise<Record<string, any>>;

export function UninstallCertFromJava(arg1:string):Promise<void>;

export function UninstallRootCA():Promise<void>;

export function UnregisterHARAssociation():Promise<void>;

export function WriteLog(arg1:string,arg2:string,arg3:string):Promise<void>;
